services:
  db:
    ports:
      - 5431:5432
    container_name: task_manager_db_con
    image: postgres:alpine
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: always
  app:
    build: .
    container_name: task_manager_app_con
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/task_manager
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
    depends_on:
      - db
    restart: always