server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    whitelist: /register,/login,/v3/api-docs,/swagger*/**,/webjars/**
  swagger:
    info:
      title: Task manager
      description: Simple task manager API project
      version: 1.0
      contact:
        name: Aleksandr Bolodurin
        email: shur026@yandex.ru
        url: https://t.me/bandit26
